<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_has_specialist extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hospital_has_specialist_model');
    } 

    /*
     * Listing of hospital_has_specialists
     */
    function index()
    {
        $data['hospital_has_specialists'] = $this->Hospital_has_specialist_model->get_all_hospital_has_specialists();
        
        $data['_view'] = 'hospital_has_specialist/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new hospital_has_specialist
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'specialist_id' => $this->input->post('specialist_id'),
				'hospital_id' => $this->input->post('hospital_id'),
            );
            
            $hospital_has_specialist_id = $this->Hospital_has_specialist_model->add_hospital_has_specialist($params);
            redirect('hospital_has_specialist/index');
        }
        else
        {            
            $data['_view'] = 'hospital_has_specialist/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a hospital_has_specialist
     */
    function edit($id)
    {   
        // check if the hospital_has_specialist exists before trying to edit it
        $data['hospital_has_specialist'] = $this->Hospital_has_specialist_model->get_hospital_has_specialist($id);
        
        if(isset($data['hospital_has_specialist']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'specialist_id' => $this->input->post('specialist_id'),
					'hospital_id' => $this->input->post('hospital_id'),
                );

                $this->Hospital_has_specialist_model->update_hospital_has_specialist($id,$params);            
                redirect('hospital_has_specialist/index');
            }
            else
            {
                $data['_view'] = 'hospital_has_specialist/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The hospital_has_specialist you are trying to edit does not exist.');
    } 

    /*
     * Deleting hospital_has_specialist
     */
    function remove($id)
    {
        $hospital_has_specialist = $this->Hospital_has_specialist_model->get_hospital_has_specialist($id);

        // check if the hospital_has_specialist exists before trying to delete it
        if(isset($hospital_has_specialist['id']))
        {
            $this->Hospital_has_specialist_model->delete_hospital_has_specialist($id);
            redirect('hospital_has_specialist/index');
        }
        else
            show_error('The hospital_has_specialist you are trying to delete does not exist.');
    }
    
}
