<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_has_service extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hospital_has_service_model');
    } 

    /*
     * Listing of hospital_has_services
     */
    function index()
    {
        $data['hospital_has_services'] = $this->Hospital_has_service_model->get_all_hospital_has_services();
        
        $data['_view'] = 'hospital_has_service/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new hospital_has_service
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'hospital_id' => $this->input->post('hospital_id'),
				'service_id' => $this->input->post('service_id'),
            );
            
            $hospital_has_service_id = $this->Hospital_has_service_model->add_hospital_has_service($params);
            redirect('hospital_has_service/index');
        }
        else
        {            
            $data['_view'] = 'hospital_has_service/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a hospital_has_service
     */
    function edit($id)
    {   
        // check if the hospital_has_service exists before trying to edit it
        $data['hospital_has_service'] = $this->Hospital_has_service_model->get_hospital_has_service($id);
        
        if(isset($data['hospital_has_service']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'hospital_id' => $this->input->post('hospital_id'),
					'service_id' => $this->input->post('service_id'),
                );

                $this->Hospital_has_service_model->update_hospital_has_service($id,$params);            
                redirect('hospital_has_service/index');
            }
            else
            {
                $data['_view'] = 'hospital_has_service/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The hospital_has_service you are trying to edit does not exist.');
    } 

    /*
     * Deleting hospital_has_service
     */
    function remove($id)
    {
        $hospital_has_service = $this->Hospital_has_service_model->get_hospital_has_service($id);

        // check if the hospital_has_service exists before trying to delete it
        if(isset($hospital_has_service['id']))
        {
            $this->Hospital_has_service_model->delete_hospital_has_service($id);
            redirect('hospital_has_service/index');
        }
        else
            show_error('The hospital_has_service you are trying to delete does not exist.');
    }
    
}
