<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_has_payment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hospital_has_payment_model');
    } 

    /*
     * Listing of hospital_has_payments
     */
    function index()
    {
        $data['hospital_has_payments'] = $this->Hospital_has_payment_model->get_all_hospital_has_payments();
        
        $data['_view'] = 'hospital_has_payment/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new hospital_has_payment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'card_id' => $this->input->post('card_id'),
				'hospital_id' => $this->input->post('hospital_id'),
            );
            
            $hospital_has_payment_id = $this->Hospital_has_payment_model->add_hospital_has_payment($params);
            redirect('hospital_has_payment/index');
        }
        else
        {            
            $data['_view'] = 'hospital_has_payment/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a hospital_has_payment
     */
    function edit($id)
    {   
        // check if the hospital_has_payment exists before trying to edit it
        $data['hospital_has_payment'] = $this->Hospital_has_payment_model->get_hospital_has_payment($id);
        
        if(isset($data['hospital_has_payment']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'card_id' => $this->input->post('card_id'),
					'hospital_id' => $this->input->post('hospital_id'),
                );

                $this->Hospital_has_payment_model->update_hospital_has_payment($id,$params);            
                redirect('hospital_has_payment/index');
            }
            else
            {
                $data['_view'] = 'hospital_has_payment/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The hospital_has_payment you are trying to edit does not exist.');
    } 

    /*
     * Deleting hospital_has_payment
     */
    function remove($id)
    {
        $hospital_has_payment = $this->Hospital_has_payment_model->get_hospital_has_payment($id);

        // check if the hospital_has_payment exists before trying to delete it
        if(isset($hospital_has_payment['id']))
        {
            $this->Hospital_has_payment_model->delete_hospital_has_payment($id);
            redirect('hospital_has_payment/index');
        }
        else
            show_error('The hospital_has_payment you are trying to delete does not exist.');
    }
    
}
