<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_reset_password extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_reset_password_model');
    } 

    /*
     * Listing of tbl_reset_password
     */
    function index()
    {
        $data['tbl_reset_password'] = $this->Tbl_reset_password_model->get_all_tbl_reset_password();
        
        $data['_view'] = 'tbl_reset_password/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_reset_password
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'email' => $this->input->post('email'),
				'activation_id' => $this->input->post('activation_id'),
				'agent' => $this->input->post('agent'),
				'client_ip' => $this->input->post('client_ip'),
				'isDeleted' => $this->input->post('isDeleted'),
				'createdBy' => $this->input->post('createdBy'),
				'createdDtm' => $this->input->post('createdDtm'),
				'updatedBy' => $this->input->post('updatedBy'),
				'updatedDtm' => $this->input->post('updatedDtm'),
            );
            
            $tbl_reset_password_id = $this->Tbl_reset_password_model->add_tbl_reset_password($params);
            redirect('tbl_reset_password/index');
        }
        else
        {            
            $data['_view'] = 'tbl_reset_password/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_reset_password
     */
    function edit($id)
    {   
        // check if the tbl_reset_password exists before trying to edit it
        $data['tbl_reset_password'] = $this->Tbl_reset_password_model->get_tbl_reset_password($id);
        
        if(isset($data['tbl_reset_password']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'email' => $this->input->post('email'),
					'activation_id' => $this->input->post('activation_id'),
					'agent' => $this->input->post('agent'),
					'client_ip' => $this->input->post('client_ip'),
					'isDeleted' => $this->input->post('isDeleted'),
					'createdBy' => $this->input->post('createdBy'),
					'createdDtm' => $this->input->post('createdDtm'),
					'updatedBy' => $this->input->post('updatedBy'),
					'updatedDtm' => $this->input->post('updatedDtm'),
                );

                $this->Tbl_reset_password_model->update_tbl_reset_password($id,$params);            
                redirect('tbl_reset_password/index');
            }
            else
            {
                $data['_view'] = 'tbl_reset_password/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_reset_password you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_reset_password
     */
    function remove($id)
    {
        $tbl_reset_password = $this->Tbl_reset_password_model->get_tbl_reset_password($id);

        // check if the tbl_reset_password exists before trying to delete it
        if(isset($tbl_reset_password['id']))
        {
            $this->Tbl_reset_password_model->delete_tbl_reset_password($id);
            redirect('tbl_reset_password/index');
        }
        else
            show_error('The tbl_reset_password you are trying to delete does not exist.');
    }
    
}
