<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_role_model');
    } 

    /*
     * Listing of tbl_roles
     */
    function index()
    {
        $data['tbl_roles'] = $this->Tbl_role_model->get_all_tbl_roles();
        
        $data['_view'] = 'tbl_role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_role
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'role' => $this->input->post('role'),
            );
            
            $tbl_role_id = $this->Tbl_role_model->add_tbl_role($params);
            redirect('tbl_role/index');
        }
        else
        {            
            $data['_view'] = 'tbl_role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_role
     */
    function edit($roleId)
    {   
        // check if the tbl_role exists before trying to edit it
        $data['tbl_role'] = $this->Tbl_role_model->get_tbl_role($roleId);
        
        if(isset($data['tbl_role']['roleId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'role' => $this->input->post('role'),
                );

                $this->Tbl_role_model->update_tbl_role($roleId,$params);            
                redirect('tbl_role/index');
            }
            else
            {
                $data['_view'] = 'tbl_role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_role you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_role
     */
    function remove($roleId)
    {
        $tbl_role = $this->Tbl_role_model->get_tbl_role($roleId);

        // check if the tbl_role exists before trying to delete it
        if(isset($tbl_role['roleId']))
        {
            $this->Tbl_role_model->delete_tbl_role($roleId);
            redirect('tbl_role/index');
        }
        else
            show_error('The tbl_role you are trying to delete does not exist.');
    }
    
}
