<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_last_login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_last_login_model');
    } 

    /*
     * Listing of tbl_last_login
     */
    function index()
    {
        $data['tbl_last_login'] = $this->Tbl_last_login_model->get_all_tbl_last_login();
        
        $data['_view'] = 'tbl_last_login/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_last_login
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'userId' => $this->input->post('userId'),
				'sessionData' => $this->input->post('sessionData'),
				'machineIp' => $this->input->post('machineIp'),
				'userAgent' => $this->input->post('userAgent'),
				'agentString' => $this->input->post('agentString'),
				'platform' => $this->input->post('platform'),
				'createdDtm' => $this->input->post('createdDtm'),
            );
            
            $tbl_last_login_id = $this->Tbl_last_login_model->add_tbl_last_login($params);
            redirect('tbl_last_login/index');
        }
        else
        {            
            $data['_view'] = 'tbl_last_login/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_last_login
     */
    function edit($id)
    {   
        // check if the tbl_last_login exists before trying to edit it
        $data['tbl_last_login'] = $this->Tbl_last_login_model->get_tbl_last_login($id);
        
        if(isset($data['tbl_last_login']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'userId' => $this->input->post('userId'),
					'sessionData' => $this->input->post('sessionData'),
					'machineIp' => $this->input->post('machineIp'),
					'userAgent' => $this->input->post('userAgent'),
					'agentString' => $this->input->post('agentString'),
					'platform' => $this->input->post('platform'),
					'createdDtm' => $this->input->post('createdDtm'),
                );

                $this->Tbl_last_login_model->update_tbl_last_login($id,$params);            
                redirect('tbl_last_login/index');
            }
            else
            {
                $data['_view'] = 'tbl_last_login/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_last_login you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_last_login
     */
    function remove($id)
    {
        $tbl_last_login = $this->Tbl_last_login_model->get_tbl_last_login($id);

        // check if the tbl_last_login exists before trying to delete it
        if(isset($tbl_last_login['id']))
        {
            $this->Tbl_last_login_model->delete_tbl_last_login($id);
            redirect('tbl_last_login/index');
        }
        else
            show_error('The tbl_last_login you are trying to delete does not exist.');
    }
    
}
