<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_user_model');
    } 

    /*
     * Listing of tbl_users
     */
    function index()
    {
        $data['tbl_users'] = $this->Tbl_user_model->get_all_tbl_users();
        
        $data['_view'] = 'tbl_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'email' => $this->input->post('email'),
				'name' => $this->input->post('name'),
				'mobile' => $this->input->post('mobile'),
				'roleId' => $this->input->post('roleId'),
				'isDeleted' => $this->input->post('isDeleted'),
				'createdBy' => $this->input->post('createdBy'),
				'createdDtm' => $this->input->post('createdDtm'),
				'updatedBy' => $this->input->post('updatedBy'),
				'updatedDtm' => $this->input->post('updatedDtm'),
            );
            
            $tbl_user_id = $this->Tbl_user_model->add_tbl_user($params);
            redirect('tbl_user/index');
        }
        else
        {            
            $data['_view'] = 'tbl_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_user
     */
    function edit($userId)
    {   
        // check if the tbl_user exists before trying to edit it
        $data['tbl_user'] = $this->Tbl_user_model->get_tbl_user($userId);
        
        if(isset($data['tbl_user']['userId']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'email' => $this->input->post('email'),
					'name' => $this->input->post('name'),
					'mobile' => $this->input->post('mobile'),
					'roleId' => $this->input->post('roleId'),
					'isDeleted' => $this->input->post('isDeleted'),
					'createdBy' => $this->input->post('createdBy'),
					'createdDtm' => $this->input->post('createdDtm'),
					'updatedBy' => $this->input->post('updatedBy'),
					'updatedDtm' => $this->input->post('updatedDtm'),
                );

                $this->Tbl_user_model->update_tbl_user($userId,$params);            
                redirect('tbl_user/index');
            }
            else
            {
                $data['_view'] = 'tbl_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_user
     */
    function remove($userId)
    {
        $tbl_user = $this->Tbl_user_model->get_tbl_user($userId);

        // check if the tbl_user exists before trying to delete it
        if(isset($tbl_user['userId']))
        {
            $this->Tbl_user_model->delete_tbl_user($userId);
            redirect('tbl_user/index');
        }
        else
            show_error('The tbl_user you are trying to delete does not exist.');
    }
    
}
