<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ci_session_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ci_session by session_id
     */
    function get_ci_session($session_id)
    {
        return $this->db->get_where('ci_sessions',array('session_id'=>$session_id))->row_array();
    }
        
    /*
     * Get all ci_sessions
     */
    function get_all_ci_sessions()
    {
        $this->db->order_by('session_id', 'desc');
        return $this->db->get('ci_sessions')->result_array();
    }
        
    /*
     * function to add new ci_session
     */
    function add_ci_session($params)
    {
        $this->db->insert('ci_sessions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ci_session
     */
    function update_ci_session($session_id,$params)
    {
        $this->db->where('session_id',$session_id);
        return $this->db->update('ci_sessions',$params);
    }
    
    /*
     * function to delete ci_session
     */
    function delete_ci_session($session_id)
    {
        return $this->db->delete('ci_sessions',array('session_id'=>$session_id));
    }
}
