<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    
    /*
     * Get tbl_user by userId
     */



    function get_hospital_info($id)
    {
        return $this->db->get_where('hospital_info',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_users
     */
    function get_all_hospital_info()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('hospital_info')->result_array();
    }

     function count_hospitals()
    {
        $this->db->from('hospital_info');
        return $this->db->count_all_results();
    }




        
    /*
     * function to add new tbl_user
     */
     function get_hospital_category()
    {
        $query = $this->db->get('hospital_category');
        $result = $query->result();

        $cat_id = array('-CHOOSE-');
        $cat_name = array('-CHOOSE-');
        
        for ($i = 0; $i < count($result); $i++)
        {
            array_push($cat_id, $result[$i]->category_id);
            array_push($cat_name, $result[$i]->category);
        }
        return array_combine($cat_id, $cat_name);
    }






   /* function add_hospitals($params)
    {
        $this->db->insert('hospital_info',$params);
        return $this->db->insert_id();
    }*/
    

        function addNewHospital($hospitalInfo)
    {
        $this->db->trans_start();
        $this->db->insert('hospital_info', $hospitalInfo);
        
        $insert_id = $this->db->insert_id();
        
        $this->db->trans_complete();
        
        return $insert_id;
    }
    




    /*
     * function to update tbl_user
     */
    function update_hospitals($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('hospital_info',$params);
    }
    
    /*
     * function to delete tbl_user
     */
    function delete_hospitals($id)
    {
        return $this->db->delete('hospital_info',array('id'=>$id));
    }
}
