<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_has_specialist_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hospital_has_specialist by id
     */
    function get_hospital_has_specialist($id)
    {
        return $this->db->get_where('hospital_has_specialists',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all hospital_has_specialists
     */
    function get_all_hospital_has_specialists()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('hospital_has_specialists')->result_array();
    }
        
    /*
     * function to add new hospital_has_specialist
     */
    function add_hospital_has_specialist($params)
    {
        $this->db->insert('hospital_has_specialists',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hospital_has_specialist
     */
    function update_hospital_has_specialist($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('hospital_has_specialists',$params);
    }
    
    /*
     * function to delete hospital_has_specialist
     */
    function delete_hospital_has_specialist($id)
    {
        return $this->db->delete('hospital_has_specialists',array('id'=>$id));
    }
}
