<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_has_service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hospital_has_service by id
     */
    function get_hospital_has_service($id)
    {
        return $this->db->get_where('hospital_has_services',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all hospital_has_services
     */
    function get_all_hospital_has_services()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('hospital_has_services')->result_array();
    }
        
    /*
     * function to add new hospital_has_service
     */
    function add_hospital_has_service($params)
    {
        $this->db->insert('hospital_has_services',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hospital_has_service
     */
    function update_hospital_has_service($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('hospital_has_services',$params);
    }
    
    /*
     * function to delete hospital_has_service
     */
    function delete_hospital_has_service($id)
    {
        return $this->db->delete('hospital_has_services',array('id'=>$id));
    }
}
