<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hospital_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    
    /*
     * Get tbl_user by userId
     */



    function get_hospital_info($id)
    {
        return $this->db->get_where('hospital_info',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_users
     */
    function get_all_hospital_info()
    {
        $this->db->order_by('id', 'asc');
        // return $this->db->get('hospital_info')->result_array();

$this->db->select("a.id, a.name, b.category, c.ownership_type, d.region_name");
    $this->db->from("hospital_info as a");
    $this->db->join('hospital_category as b', 'a.category_id = b.category_id');
    $this->db->join('hospital_ownership as c', 'a.ownership_id = c.ownership_id'); 
    $this->db->join('regions as d', 'a.region_id = d.region_id');         
       // join $query = $this ->db->get('services')
        //return $query->result();
    $query = $this->db->get();
      $result = $query->result_array();
    return $result;
    

    }

     function count_hospitals()
    {
        $this->db->from('hospital_info');
        return $this->db->count_all_results();
    }



        
    /*
     * function to add new tbl_user
     */
     function get_hospital_category()
    {
        $query = $this->db->get('hospital_category');
        $result = $query->result();

        $cat_id = array('-CHOOSE-');
        $cat_name = array('-CHOOSE-');
        
        for ($i = 0; $i < count($result); $i++)
        {
            array_push($cat_id, $result[$i]->category_id);
            array_push($cat_name, $result[$i]->category);
        }
        return array_combine($cat_id, $cat_name);
    }

 function get_hospital_ownership()
    {
        $query = $this->db->get('hospital_ownership');
        $result = $query->result();

        $cat_id = array('-CHOOSE-');
        $cat_name = array('-CHOOSE-');
        
        for ($i = 0; $i < count($result); $i++)
        {
            array_push($cat_id, $result[$i]->ownership_id);
            array_push($cat_name, $result[$i]->ownership_type);
        }
        return array_combine($cat_id, $cat_name);
    }


  function get_regions()
    {
        $query = $this->db->get('regions');
        $result = $query->result();

        $cat_id = array('-CHOOSE-');
        $cat_name = array('-CHOOSE-');
        
        for ($i = 0; $i < count($result); $i++)
        {
            array_push($cat_id, $result[$i]->region_id);
            array_push($cat_name, $result[$i]->region_name);
        }
        return array_combine($cat_id, $cat_name);
    }

   /* function add_hospitals($params)
    {
        $this->db->insert('hospital_info',$params);
        return $this->db->insert_id();
    }*/
    

        function addNewHospital($hospitalInfo)
    {
        $this->db->trans_start();
        $this->db->insert('hospital_info', $hospitalInfo);
        
        $insert_id = $this->db->insert_id();
        
        $this->db->trans_complete();
        
        return $insert_id;
    }
    




    /*
     * function to update tbl_user
     */
    function update_hospitals($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('hospital_info',$params);
    }
    
    /*
     * function to delete tbl_user
     */
    function delete_hospitals($id)
    {
        return $this->db->delete('hospital_info',array('id'=>$id));
    }
}
