<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Payment_service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get payment_service by id
     */
    function get_payment_service($id)
    {
        return $this->db->get_where('payment_service',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all payment_service
     */
    function get_all_payment_service()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('payment_service')->result_array();
    }
        
    /*
     * function to add new payment_service
     */
    function add_payment_service($params)
    {
        $this->db->insert('payment_service',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update payment_service
     */
    function update_payment_service($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('payment_service',$params);
    }
    
    /*
     * function to delete payment_service
     */
    function delete_payment_service($id)
    {
        return $this->db->delete('payment_service',array('id'=>$id));
    }
}
