<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_role by roleId
     */
    function get_tbl_role($roleId)
    {
        return $this->db->get_where('tbl_roles',array('roleId'=>$roleId))->row_array();
    }
        
    /*
     * Get all tbl_roles
     */
    function get_all_tbl_roles()
    {
        $this->db->order_by('roleId', 'desc');
        return $this->db->get('tbl_roles')->result_array();
    }
        
    /*
     * function to add new tbl_role
     */
    function add_tbl_role($params)
    {
        $this->db->insert('tbl_roles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_role
     */
    function update_tbl_role($roleId,$params)
    {
        $this->db->where('roleId',$roleId);
        return $this->db->update('tbl_roles',$params);
    }
    
    /*
     * function to delete tbl_role
     */
    function delete_tbl_role($roleId)
    {
        return $this->db->delete('tbl_roles',array('roleId'=>$roleId));
    }
}
