<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_user by userId
     */
    function get_tbl_user($userId)
    {
        return $this->db->get_where('tbl_users',array('userId'=>$userId))->row_array();
    }
        
    /*
     * Get all tbl_users
     */
    function get_all_tbl_users()
    {
        $this->db->order_by('userId', 'desc');
        return $this->db->get('tbl_users')->result_array();
    }
        
    /*
     * function to add new tbl_user
     */
    function add_tbl_user($params)
    {
        $this->db->insert('tbl_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_user
     */
    function update_tbl_user($userId,$params)
    {
        $this->db->where('userId',$userId);
        return $this->db->update('tbl_users',$params);
    }
    
    /*
     * function to delete tbl_user
     */
    function delete_tbl_user($userId)
    {
        return $this->db->delete('tbl_users',array('userId'=>$userId));
    }
}
