<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_reset_password_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_reset_password by id
     */
    function get_tbl_reset_password($id)
    {
        return $this->db->get_where('tbl_reset_password',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_reset_password
     */
    function get_all_tbl_reset_password()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_reset_password')->result_array();
    }
        
    /*
     * function to add new tbl_reset_password
     */
    function add_tbl_reset_password($params)
    {
        $this->db->insert('tbl_reset_password',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_reset_password
     */
    function update_tbl_reset_password($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_reset_password',$params);
    }
    
    /*
     * function to delete tbl_reset_password
     */
    function delete_tbl_reset_password($id)
    {
        return $this->db->delete('tbl_reset_password',array('id'=>$id));
    }
}
