<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_last_login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_last_login by id
     */
    function get_tbl_last_login($id)
    {
        return $this->db->get_where('tbl_last_login',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_last_login
     */
    function get_all_tbl_last_login()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_last_login')->result_array();
    }
        
    /*
     * function to add new tbl_last_login
     */
    function add_tbl_last_login($params)
    {
        $this->db->insert('tbl_last_login',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_last_login
     */
    function update_tbl_last_login($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_last_login',$params);
    }
    
    /*
     * function to delete tbl_last_login
     */
    function delete_tbl_last_login($id)
    {
        return $this->db->delete('tbl_last_login',array('id'=>$id));
    }
}
